# Generated by Django 6.0.7 on 2026-07-29 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='captures/')),
                ('filter_used', models.CharField(choices=[('original', 'Original'), ('rbr', 'RBR Mode'), ('mono', 'Mono'), ('speed', 'Speed')], default='original', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
